# Generated by Django 4.2.7 on 2024-01-12 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_pa', models.CharField(max_length=50)),
                ('espece', models.CharField(max_length=50)),
                ('race', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('antecedants_medicaux', models.CharField(max_length=50)),
                ('sexe', models.CharField(choices=[('male', 'male'), ('femelle', 'femelle')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Veterinaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_ve', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('specialiter', models.CharField(default='', max_length=50)),
                ('adresse', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('telephone', models.IntegerField()),
                ('sexe', models.CharField(choices=[('homme', 'Homme'), ('femme', 'Femme')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Traitement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_traitement', models.DateField()),
                ('medicament', models.CharField(max_length=50)),
                ('dosages', models.CharField(max_length=50)),
                ('instructions', models.CharField(max_length=250)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trai_patient', to='app_patient.patient')),
                ('veterinaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trai_veterinaire', to='app_patient.veterinaire')),
            ],
        ),
        migrations.CreateModel(
            name='Rendezvous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.CharField(max_length=50)),
                ('observation', models.CharField(max_length=250)),
                ('date', models.DateField()),
                ('heure', models.TimeField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rdv_patient', to='app_patient.patient')),
                ('veterinaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rdv_veterinaire', to='app_patient.veterinaire')),
            ],
        ),
        migrations.CreateModel(
            name='Proprietaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_pro', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('adresse', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('telephone', models.IntegerField()),
                ('sexe', models.CharField(choices=[('homme', 'Homme'), ('femme', 'Femme')], max_length=20)),
                ('patient', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='prop_patient', to='app_patient.patient')),
            ],
        ),
    ]
